### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by AmritasyaPutra** [dregad/dokuwiki-plugin-addnewpage#90] opened 2023-02-03 07:39 UTC
The plugins page says it is compatible with 2022-07-31 "Igor" but I am getting the following Warning with my PHP 8.1 installation:
[01-Feb-2023 23:33:43 Asia/Kolkata] PHP Warning: Undefined array key 1 in /home/ekvastra/wiki.ekvastra.in/lib/plugins/addnewpage/syntax.php on line 66

**Comment by eduardomozart** [comment] 2023-02-05 13:57
Hello,
Try to add the following to your plugin ``syntax.php`` file on line 66:
```
-        $templates = explode(',', $options[1]);
+        if (isset($options[1])) {
+            $templates = explode(',', $options[1]);
+        } else {
+            $templates = array();
+        }
```
I received the same error as you only the first time I opened the page after installing the plug-in, so I do not know if this fixes the issue. If it fixes, please let me know I'll create a PR with this fix.

**Comment by AmritasyaPutra** [comment] 2023-02-21 10:34
I have made the change locally on my setup, I will let you know how it goes in a few days time.

**Comment by dregad** [comment] 2023-05-07 15:35
Duplicate of #91

**Closed by dregad** 2023-05-07 15:35 UTC
Labels: duplicate
