### ISSUE TITLE
Users denied permission to add pages

### ISSUE THREAD

**Issue by jamie-lynne** [dregad/dokuwiki-plugin-addnewpage#40] opened 2015-03-06 20:55 UTC
I have set the start page of each namespace to have the "add new page to that namespace" box. My users are seeing "You are not allowed to add pages" when they have Delete rights in ACLs. The only users who can still see the add new page box are the Superusers I put in the configuration manager.

**Comment by Olivier-Axion** [comment] 2015-07-08 14:55
DokuWiki speeds up browsing through the wiki by [caching parsed files] (https://www.dokuwiki.org/caching?). Did you try to prevent the page from being cached by using the NOCACHE tag? 

`~~NOCACHE~~`

**Comment by sshafiullah** [comment] 2015-07-08 17:38
Placing NOCACHE on the page that contains the form solves this issue. I suggest placing this solution prominently on the README as the plugin is unusable without it

**Comment by blueduckdock** [comment] 2016-01-22 15:42
Thanks @sshafiullah 
I use this extension on our sidebar to easily add links. It was broken when new users logged in (all permissions reflected solely their own.) Placing ~~NOCACHE~~ on that though fixed it so now everyone only has access to add pages that they are a group of.

Cheers

**Comment by simpelpimpel** [comment] 2016-03-29 17:26
Doesnt work for me. 

Nocache-tag doesnt work
Reducing the maximum age for caching (to 1 or even -1 seconds) doesnt work
Deactivating/reactivating doesnt work
Reinstalling doesnt work
Uninstalling/installing doesnt work

It allways shows "You are not allowed to add pages" with either Users or Superusers... 
ACLs are set right...

what else can I try?

**Comment by thorpj** [comment] 2017-02-06 16:03
Has there been any progress on this issue?

**Comment by dregad** [comment] 2023-05-07 15:44
Looks like a duplicate of #38

**Closed by dregad** 2023-05-07 15:44 UTC
