### ISSUE TITLE
ACL Check doesn't work properly

### ISSUE THREAD

**Issue by achimKi** [dregad/dokuwiki-plugin-addnewpage#68] opened 2017-01-23 13:52 UTC
1) the plug-in seems to Register for **_any_** Check-ACL Event:
   $contr->register_hook('DOKUWIKI_STARTED', 'AFTER', $this, 'check_acl', array());
   When I add a simple echo Statement in function check_acl, then it appears on any page, **_wherever I 
   navigate in my wiki_**
   Is this really intended?
2) the check_acl function refuses access for any user but the @admin to read the template file
![permission-denied](https://cloud.githubusercontent.com/assets/25243644/22206291/f4eef56e-e17a-11e6-86c7-560d80eadba4.jpg)
   although the template file is readable (even writable) for a user of group @author
![wiki-screenshot_23012017_131324_004-red](https://cloud.githubusercontent.com/assets/25243644/22206375/57d8a27e-e17b-11e6-900a-e4bbb73ea9b7.jpg)

**Comment by dregad** [comment] 2023-05-07 15:45
Related, possibly duplicate of #38 - can you check if the suggested ~~NOCACHE~~ workaround fixes the problem

**Comment by dregad** [comment] 2024-09-14 09:46
You did not provide any feedback so I assume you're OK with closing this as duplicate of #38. Feel free to reopen if not.

**Closed by dregad** 2024-09-14 09:46 UTC
Labels: duplicate
